#  LOCALHOST
###
GET http://localhost:8080/projects HTTP/1.1
###
GET http://localhost:8080/projects/647053abe793550ab516ff65 HTTP/1.1
###
GET http://localhost:8080/projects/646dacf77eee884597889206 HTTP/1.1
###
GET http://localhost:8080/projects/646dacf77eee884597889207 HTTP/1.1


# Create a project
### 
POST http://localhost:8080/projects HTTP/1.1
content-type: application/json

{
      "jeepName": "2001 TJ",
      "projectName": "Cam shaft position sensor",
      "description": "low engine performance causing errors and eventually undrivable",
      "partNeeded1": "",
      "partNeeded2": "",
      "partsOnhand": true,
      "startDate": "05/27/2023",
      "hoursToComplete": "1"
}

# Update a project
###
PUT http://localhost:8080/projects/6470e8a20ddea826aa39ac93 HTTP/1.1
content-type: application/json

{
      "jeepName": "2001 TJ",
      "projectName": "Cam shaft position sensor",
      "description": "low engine performance causing errors and eventually undrivable",
      "partNeeded1": "position sensor",
      "partNeeded2": "",
      "partsOnhand": true,
      "startDate": "05/27/2023",
      "hoursToComplete": "2"
}


# Delete a contact
###
DELETE http://localhost:8080/projects/6470e8a20ddea826aa39ac93 HTTP/1.1



#  PRODUCTION Deploy
###
GET https://jeepprojects.onrender.com/projects HTTP/1.1
###
GET https://jeepprojects.onrender.com/projects/644d8fac48a57a41ab7ece74 HTTP/1.1
###
GET https://jeepprojects.onrender.com/projects/644d902d48a57a41ab7ece75 HTTP/1.1
###
GET https://jeepprojects.onrender.com/projects/644d908c48a57a41ab7ece76 HTTP/1.1


# Create a Contact
###
POST https://jeepprojects.onrender.com/projects HTTP/1.1
content-type: application/json

{
      "jeepName": "2001 TJ",
      "projectName": "Cam shaft position sensor",
      "description": "low engine performance causing errors and eventually undrivable",
      "partNeeded1": "",
      "partNeeded2": "",
      "partsOnhand": true,
      "startDate": "05/27/2023",
      "hoursToComplete": "1"
}


# Update a Contact
###
PUT https://jeepprojects.onrender.com/projects/6456d88d8e52761e61252765 HTTP/1.1
content-type: application/json

{
      "jeepName": "2001 TJ",
      "projectName": "Cam shaft position sensor",
      "description": "low engine performance causing errors and eventually undrivable",
      "partNeeded1": "position sensor",
      "partNeeded2": "",
      "partsOnhand": true,
      "startDate": "05/27/2023",
      "hoursToComplete": "2"
}



# Delete a Contact
###
DELETE https://jeepprojects.onrender.com/projects/6456d88d8e52761e61252765 HTTP/1.1




# **********************************************************************************
# **********************************************************************************

#  LOCALHOST
###
GET http://localhost:8080/trips HTTP/1.1
###
GET http://localhost:8080/trips/6488f43a9b0eda6d58c198bd HTTP/1.1
###
GET http://localhost:8080/trips/6488f43a9b0eda6d58c198be HTTP/1.1
###
GET http://localhost:8080/trips/6488f43a9b0eda6d58c198bf HTTP/1.1


# Create a trip
### 
POST http://localhost:8080/trips HTTP/1.1
content-type: application/json

{
    "tripName": "Strawberry Lake",
    "description": "Day trip to strawberry lake stopping at westlake along the way",
    "friendOnTrip": "Smart Family",
    "vehicle": "Jeep TJ",
    "camping": false,
    "tripDate": "7/2/2023",
    "numberOfNights": "0",
    "milesFromHouse": "45"
}

# Update a trip
###
PUT http://localhost:8080/trips/6470e8a20ddea826aa39ac93 HTTP/1.1
content-type: application/json

{
    "tripName": "Strawberry Lake and West Lake",
    "description": "Day trip to strawberry lake stopping at westlake along the way",
    "friendOnTrip": "Smart Family",
    "vehicle": "Jeep JK",
    "camping": true,
    "tripDate": "7/2/2023",
    "numberOfNights": "3",
    "milesFromHouse": "45"
}


# Delete a trip
###
DELETE http://localhost:8080/trips/6470e8a20ddea826aa39ac93 HTTP/1.1



#  PRODUCTION Deploy
###
GET https://jeepprojects.onrender.com/trips HTTP/1.1
###
GET https://jeepprojects.onrender.com/trips/6488f43a9b0eda6d58c198bd HTTP/1.1
###
GET https://jeepprojects.onrender.com/trips/6488f43a9b0eda6d58c198be HTTP/1.1
###
GET https://jeepprojects.onrender.com/trips/6488f43a9b0eda6d58c198bf HTTP/1.1


# Create a trip
###
POST https://jeepprojects.onrender.com/trips HTTP/1.1
content-type: application/json

{
    "tripName": "Strawberry Lake",
    "description": "Day trip to strawberry lake stopping at westlake along the way",
    "friendOnTrip": "Smart Family",
    "vehicle": "Jeep TJ",
    "camping": false,
    "tripDate": "7/2/2023",
    "numberOfNights": "0",
    "milesFromHouse": "45"
}


# Update a trip
###
PUT https://jeepprojects.onrender.com/trips/6456d88d8e52761e61252765 HTTP/1.1
content-type: application/json

{
    "tripName": "Strawberry Lake and West Lake",
    "description": "Day trip to strawberry lake stopping at westlake along the way",
    "friendOnTrip": "Smart Family",
    "vehicle": "Jeep JK",
    "camping": true,
    "tripDate": "7/2/2023",
    "numberOfNights": "3",
    "milesFromHouse": "45"
}



# Delete a trip
###
DELETE https://jeepprojects.onrender.com/trips/6456d88d8e52761e61252765 HTTP/1.1

